# Generated by Django 4.0.2 on 2022-02-15 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_owner_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='owner',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
